apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: apacheds
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: apacheds
    spec:
      containers:
      - name: apacheds
        image: "joshmoore/apacheds-docker:restart"
        envFrom:
        - secretRef:
            name: apacheds-config-private
        ports:
        - name: apacheds
          containerPort: 10389
        volumeMounts:
        - name: apacheds-files
          mountPath: /var/lib/apacheds
          subPath: files

      volumes:
      - name: apacheds-files
        persistentVolumeClaim:
          claimName: apacheds-volume
